# Generated by Django 2.0.13 on 2019-11-18 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id_admin', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=45)),
                ('haslo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='kategoria',
            fields=[
                ('id_kategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='klient',
            fields=[
                ('id_klient', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=100)),
                ('haslo', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('adres', models.CharField(max_length=45)),
                ('kod_pocztowy', models.CharField(max_length=45)),
                ('miasto', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='towar',
            fields=[
                ('id_towar', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa_towaru', models.CharField(max_length=45)),
                ('cena_brutto', models.FloatField(default=0)),
                ('cena_netto', models.FloatField(default=0)),
                ('id_kategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='zamowienie',
            fields=[
                ('id_zamowienie', models.IntegerField(primary_key=True, serialize=False)),
                ('ilosc', models.IntegerField(default=0)),
                ('data_zamowienia', models.DateTimeField(auto_now_add=True)),
                ('id_klient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.klient')),
                ('id_towar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.towar')),
            ],
        ),
    ]
