# Generated by Django 2.0.13 on 2019-11-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='uzytownik',
        ),
    ]
